export const Questions = [
    {
      prompt: "Which computer launch date",
      optionA: "1948",
      optionB: "1946",
      optionC: "1944",
      optionD: "1943",
      asnwer: "optionD",
    },
    {
        prompt: "Which smallest ocean in the world",
        optionA: "Indian",
        optionB: "Pacific",
        optionC: "Atlantic",
        optionD: "Arctic",
        asnwer: "optionD",
      },
      {
        prompt: "Which ocean Bermuda Triangle region is located",
        optionA: "Atlantic",
        optionB: "Indian",
        optionC: "Pacific",
        optionD: "Arctic",
        asnwer: "optionA",
      },
      {
        prompt: "Which country is known as the Playground of Europe",
        optionA: "Austria",
        optionB: "Holland",
        optionC: "Switzerland",
        optionD: "Italy",
        asnwer: "optionC",
      },
      {
        prompt: "Which country white elephant is found",
        optionA: "India",
        optionB: "Srilanka",
        optionC: "Thailand",
        optionD: "Malaysia",
        asnwer: "optionC",
        
      },
      {
        prompt: "Total number of ocean in the world is",
        optionA: "3",
        optionB: "5",
        optionC: "7",
        optionD: "12",
        asnwer: "optionB",
        
      },
      {
        prompt: "Which animal is known as the Ship of the Desert",
        optionA: "Lion",
        optionB: "Tiger",
        optionC: "Hourse",
        optionD: "camel",
        asnwer: "optionD",
        
      },
      {
        prompt: "Which Indian state produces the largest quantity of pulses",
        optionA: "Maharashtra",
        optionB: "Uttar Pradesh",
        optionC: "Madhya Pradesh",
        optionD: "Rajasthan",
        asnwer: "optionC",
        
      },
      {
        prompt: "Which crop sown on the largest area in india",
        optionA: "Rice",
        optionB: "Wheat",
        optionC: "sugarcane",
        optionD: "Maize",
        asnwer: "optionA",
      },
      {
        prompt: "Who is known as The Saint of Gutters",
        optionA: "Baba Amte",
        optionB: "Mother Teresa",
        optionC: "Anna Hazare",
        optionD: "None of these",
        asnwer: "optionB",
      },
      {
        prompt: "Grand central terminal park avenue new york is the World's",
        optionA: "largest railway station",
        optionB: "highest railway station",
        optionC: "longest railway station",
        optionD: "None of the above",
        asnwer: "optionA",
      },
      {
        prompt: "Name the person who was also known as Deshbandhu",
        optionA: "S.Radhakrishnan",
        optionB: "G.K.Gokhale",
        optionC: "Chittarajan Das",
        optionD: "Madan mohan malviya",
        asnwer: "optionC",
      },
      {
        prompt: "FFC stands for",
        optionA: "Foreign Finance Corporation",
        optionB: "Film Finace Corporation",
        optionC: "Federation of Football Council",
        optionD: "None of the above",
        asnwer: "optionB",
      },
      {
        prompt: "The capital of Uttarakhand is",
        optionA: "Masoorie",
        optionB: "Dehra Dun",
        optionC: "Nainital",
        optionD: "None of these",
        asnwer: "optionB",
      },
      {
        prompt: "In which state has the largest area",
        optionA: "Maharashtra",
        optionB: "Madhya Pradesh",
        optionC: "Uttar Pradesh",
        optionD: "Rajasthan",
        asnwer: "optionD",
      },
      {
        prompt: "Geet Govind is a famous creation of",
        optionA: "Bana Bhatt",
        optionB: "Kalidas",
        optionC: "Jayadev",
        optionD: "Bharat Muni",
        asnwer: "optionC",
      },
      {
        prompt: "When did the world trade organization come into existence",
        optionA: "1992",
        optionB: "1993",
        optionC: "1994",
        optionD: "1995",
        asnwer: "optionD",
      },
      {
        prompt: "In which year did the cabinet Mission arrived in India",
        optionA: "1942",
        optionB: "1943",
        optionC: "1945",
        optionD: "1946",
        asnwer: "optionD",
      },
      {
        prompt: "Golf player vijay singh belong to which country",
        optionA: "Usa",
        optionB: "Fiji",
        optionC: "India",
        optionD: "Uk",
        asnwer: "optionB",
      },
      {
        prompt: "Which state has the largest population",
        optionA: "Uttar Pradesh",
        optionB: "Maharastra",
        optionC: "Bihar",
        optionD: "Andra pradesh",
        asnwer: "optionA",
      },
      

  ];